[package]
name = "gba_ui_sdl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba_core = { path = "../gba_core" }
sdl2 = "0.35.1"